# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
version: 2

updates:

  - package-ecosystem: "npm"

    directory: "/"

  - package-ecosystem: "composer"

    directory: "composer.json"
    schedule.
    intervalschedule.
    dayschedule.
    timeschedule.
    timezonepull-request-branch-name.separatororg
    .opencontainers
.image.sourcebuild.gradle.ktsrequirements.txtpom.xmlpyproject
.tomlpackage
.jsoncomposer.jsondependable.ymlbuild.gradlejust 

Updated the dependabot.yml file to configure Dependabot to monitor for updates

 to the npm and composer package managers. 
    This will help to ensure that my project is always using 
    the latest versions of its dependencies, 
    which can help to improve security and stability.

If you have any questions or concerns, please feel free to let me know.







